version: '3.8'

services:
  web:
    image: php:latest
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:80 -t public
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=your_app_key_here
