name: Build and Push Docker Image to Docker Hub
on:
  push:
    branches:
      - master

jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish to Github packages
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/next:latest
            docker.pkg.github.com/${{ github.repository }}/next:${{ github.run_number }}

      - name: Publish to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: |
            tuzuka/laravel-app:latest
            tuzuka/laravel-app:${{ github.run_number }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
