name: Build and Push Docker Image to Docker Hub
on:
  push:
    branches:
      - master

jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish to Github packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/next
          tag: latest, ${{ github.run_number }}

      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tuzuka/laravel-app
          tag: latest

      - name: Build Docker image
        run: docker build -t tuzuka/laravel-app:latest .

      - name: Push Docker image
        run: docker push tuzuka/laravel-app:latest
